package com.github.axodenelcorvus.entry;


//Does not include primary key that is expected to be autogenerated by database
public record PokemonSpriteEntry(int pokemonID,
                                String spriteFormDescriptor,
                                String imgFilePath) implements SqlTupleSerializable {

    public String toSqlTuple(SqlStringResolver sqlStrResolution) {
        return  "(%d, %s, %s)".formatted(
                pokemonID,
                spriteFormDescriptor,
                imgFilePath
        );
    }

}
