package com.github.axodenelcorvus.entry;


//Does not include primary key that is expected to be autogenerated by database
public record PokemonSpriteEntry(int pokemonID,
                                String spriteFormDescriptor,
                                String staticImgResourcePath) implements SqlTupleSerializable {


    public static String TABLE_NAME = "significant_sprite_forms";
    public static String COLUMN_LIST = "(pokemon_id, name, static_img_resource_path)";

    public String toSqlTuple(SqlStringResolver sqlStrResolution) {
        return  "(%d, %s, %s)".formatted(
                pokemonID,
                spriteFormDescriptor,
                staticImgResourcePath
        );
    }

}
