package com.github.axodenelcorvus.model.entry;


//Does not include primary key that is expected to be autogenerated by database
public final class PokemonSpriteEntry implements SqlTupleSerializable {

    private final int pokemonId;
    private final String spriteFormDescriptor;
    private final String staticImgResourcePath;


    public PokemonSpriteEntry(int pokemonId, GenderSpriteForm genderForm, int nationalDexId) {
        this(pokemonId, genderForm, RegionalForm.STANDARD, nationalDexId);
    }

    public PokemonSpriteEntry(int pokemonId, GenderSpriteForm genderForm, RegionalForm region, int nationalDexId) {
        String genderFormDescriptor = findGenderDescriptor(genderForm);
        String regionalFormDescriptor = "";

        String[] staticImgResourcePath = { "universal_default", String.valueOf(nationalDexId) };

        if (genderForm.equals(GenderSpriteForm.FEMALE))
            staticImgResourcePath[0] = "female";

        if (!region.equals(RegionalForm.STANDARD)) {
            var regionName = region.name().toLowerCase();
            regionalFormDescriptor = Character.toUpperCase(regionName.charAt(0)) + regionName.substring(1);
            staticImgResourcePath[1] += "_" + regionName;
        }

        this.pokemonId = pokemonId;
        this.staticImgResourcePath = String.join("/", staticImgResourcePath) + ".png";
        this.spriteFormDescriptor = String.join(" ", genderFormDescriptor, regionalFormDescriptor);
    }

    private String findGenderDescriptor(GenderSpriteForm genderForm) {
        return switch (genderForm) {
            case GenderSpriteForm.MALE ->   "Male";
            case GenderSpriteForm.FEMALE -> "Female";
            case GenderSpriteForm.NONE ->   "Default";
        };
    }

    public int getForeignKey() {
        return pokemonId;
    }

    public String getSpriteFormDescriptor() {
        return spriteFormDescriptor;
    }

    public String getStaticImgResourcePath() {
        return staticImgResourcePath;
    }


    public static String TABLE_NAME = "significant_sprite_forms";
    public static String COLUMN_LIST = "(pokemon_id, name, static_img_resource_path)";

    public String toSqlTuple(SqlStringResolver sqlStrResolution) {
        return  "(%d, %s, %s)".formatted(
                pokemonId,
                spriteFormDescriptor,
                staticImgResourcePath
        );
    }

}
